### ISSUE TITLE
Country details freeze on mobile Firefox when time slider is used

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap-contrib#1463]
Tested in Firefox 60.0.2 on Android.

Steps to repro:
- choose a region from map, e.g. Germany
- slide the time slider into the past
- go into "Areas" list or "Map" view again
- choose another region, e.g. France
- observed behaviour:
  - time slider is kept at previously chosen value (I presume this is intended).
  - country name and "current" production values are also kept at last seen values, rather than changing to the values for the new country. That is, Germany, German wind production, and German wind capacity are shown.
  - 24 hour charts, however, display values for the newly chosen country. 
  - moving the time slider resets country name and "current" production to the expected values.

I can't reproduce on desktop in recent version of Webkit (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.114 Safari/537.36 Vivaldi/1.9.818.50). I don't have a recent version of Firefox desktop right now so I can't tell if this is actually a Firefox issue...

**Comment by systemcatch** [comment]
I see this in Firefox 60.0.2 on Ubuntu and 60.0.1 on Android 6.0.

**Comment by corradio** [comment]
Might be fixed by https://github.com/tmrowco/electricitymap/pull/1459

**Comment by jarek** [comment]
I actually still see this issue on mobile Firefox 60.0.2

**Comment by lorrieq** [comment]
The country detail freeze is fixed but I still get no data in the country detail when on mobile (using Safari)

![image1](https://user-images.githubusercontent.com/6525086/42095562-dde280ae-7baa-11e8-9ad3-b0e7030ec2b5.PNG)

**Comment by corradio** [comment]
@lorrieq does the issue still happen? What phone do you use?
Can you describe the exact steps to reproduce?

**Comment by lorrieq** [comment]
Hey, it was Safari on iPhone SE. But it seems to have been fixed since and looks great now!

**Comment by corradio** [comment]
Great!

**Comment by jarek** [comment]
BTW, I actually _still_ see this issue, now on mobile Firefox 62.0.2. Possibly related to #1671?

**Comment by jarek** [comment]
I still see this issue on Android Firefox 64.0.2, steps to reproduce are as in first comment, observed behaviour remained the same, except time slider starts at earliest value then jumps to the most recent value after about a second (even though time display under region name is unchanged).

**Comment by corradio** [comment]
@jarek do you still have the issue?

**Comment by jarek** [comment]
Yes actually, with steps to reproduce as in the first post. Currently Firefox 68.3.0, Android.

**Comment by corradio** [comment]
Is this still happening in the *web* version of electricityMap (not the app)?

**Comment by jarek** [comment]
Seems fine now! Unable to reproduce on Firefox 68.9.0. Will close the issue, thank you!
